In [2]:
import numpy as np

In [4]:
A = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(A)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [7]:
#transpose
transpose = np.transpose(A)
print(transpose)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [8]:
#determinant
determinant = np.linalg.det(A)
print(determinant)

0.2299999999999999


In [11]:
#decompose
decompose = np.linalg.cholesky(A)
decompose

array([[1.        , 0.        , 0.        ],
       [0.2       , 0.9797959 , 0.        ],
       [0.5       , 0.71443451, 0.48947251]])

In [ ]:
#decompose using the eigen values and vectors
Decompose = np.linalg.eig(A)
print(Decompose)

EigResult(eigenvalues=array([2.04100779, 0.82188052, 0.13711169]), eigenvectors=array([[-0.43721717, -0.85359707, -0.28321933],
       [-0.59931898,  0.51133314, -0.61591816],
       [-0.67056536,  0.09955128,  0.73514055]]))


In [16]:
#transform
transform = np.linalg.inv(A)
print(transform)

[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]
